version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: articles-db
    restart: always
    environment:
      POSTGRES_DB: articles
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"  # Для обеспечения правильной кодировки
    ports:
      - "5432:5432"
    volumes:
      - articles_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d  # Подключаем папку с миграциями
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d articles" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Укажите ваш email
      PGADMIN_DEFAULT_PASSWORD: secret          # Укажите ваш пароль
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

  app:
    build: .
    container_name: spring-boot-app
    depends_on:
#      - postgres
      postgres:
        condition: service_healthy
#
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/articles
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/articles       # Работа приложения в докере
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - app-network

  data-generator:
    image: python:3.9-alpine
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./:/app  # Монтируем текущую директорию
    working_dir: /app
    command: sh -c "pip install psycopg2-binary faker && python generate_data.py"
    environment:
      DB_HOST: postgres  # Имя сервиса в Docker-сети
      DB_PORT: 5432
      DB_NAME: articles
      DB_USER: admin
      DB_PASSWORD: secret
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  articles_data:
