services:
  postgres:
    image: postgres:15
    container_name: articles-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"  # Для обеспечения правильной кодировки
    ports:
      - "5432:5432"
    volumes:
      - articles_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d  # Подключаем папку с миграциями
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app-network

  main-service:
    build: .
    container_name: spring-boot-app
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_FLYWAY_URL: ${SPRING_FLYWAY_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      SERVER_TOMCAT_MAX_THREADS: ${SERVER_TOMCAT_MAX_THREADS}
      SPRING_JPA_SHOW_SQL: ${SPRING_JPA_SHOW_SQL}
#      KAFKA_HOSTS: ${KAFKA_HOSTS:-hl22.zil:9094,hl23.zil:9094}
#      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID:-seryak0ff-consumer-group}
#      KAFKA_TOPIC: ${KAFKA_TOPIC:-var17}
#      KAFKA_CONCURRENCY: ${KAFKA_CONCURRENCY:-2}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network

  analytics-service:
    build: ../analytics-service
    container_name: analytics-service
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
    environment:
      MODULE1_SERVICE_URL: http://main-service:8080
    ports:
      - "8081:8081"
    depends_on:
      - main-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  articles_data:
