apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: var17
data:
  DB_HOST: "10.60.3.26"
  DB_PORT: "5432"
  DB_NAME: "articles"
  SPRING_DATASOURCE_USERNAME: "postgres"
  #  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.minikube.internal:5432/articles"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://10.60.3.26:5432/articles"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_FLYWAY_URL: "jdbc:postgresql://10.60.3.26:5432/articles"
  #  SPRING_FLYWAY_URL: "jdbc:postgresql://host.minikube.internal:5432/articles"
  MODULE1_SERVICE_URL: "http://main-service:8080"
  #KAFKA_HOSTS: "hl22.zil:9094,hl23.zil:9094"
  #KAFKA_GROUP_ID: "seryak0ff-consumer-group"
  #KAFKA_TOPIC: "var17"
  #KAFKA_CONCURRENCY: "2"
  SERVER_TOMCAT_MAX_THREADS: "200"