apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: var17
data:
  DB_HOST: "10.60.3.26"
  DB_PORT: "5432"
  DB_NAME: "articles"
  SPRING_DATASOURCE_USERNAME: "postgres"
  #  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.minikube.internal:5432/articles"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://10.60.3.26:5432/articles"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_FLYWAY_URL: "jdbc:postgresql://10.60.3.26:5432/articles"
  #  SPRING_FLYWAY_URL: "jdbc:postgresql://host.minikube.internal:5432/articles"
  MODULE1_SERVICE_URL: "http://main-service:8080"
  #KAFKA_HOSTS: "hl22.zil:9094,hl23.zil:9094"
  #KAFKA_GROUP_ID: "seryak0ff-consumer-group"
  #KAFKA_TOPIC: "var17"
  #KAFKA_CONCURRENCY: "2"
  SERVER_TOMCAT_MAX_THREADS: "200"

  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "always"
  CORE_CRASH_DELAY: "10000"


  # 1 VAR
  RESILIENCE4J_MODE: "retry"  # retry or circuitbreaker
  # For retry
  RETRY_ENABLED: "true"
  RETRY_MAX_ATTEMPTS: "7"
  RETRY_WAIT_DURATION: "10s"

  # For circuitBreaker
  CB_ENABLED: "false"
  CB_FAILURE_RATE: "10"
  CB_WAIT_DURATION: "5s" # 5s, 10s or 20s
  CB_SLIDING_WINDOW: "5"


#  # 2 VAR
#  RESILIENCE4J_MODE: "circuitbreaker"
#  # For retry
#  RETRY_ENABLED: "false"
#  #RETRY_MAX_ATTEMPTS: "7"
#  #RETRY_WAIT_DURATION: "10s"
#
#  # For circuitBreaker
#  CB_ENABLED: "true"
#  CB_FAILURE_RATE: "10"  # можно поменять почекать
#  CB_WAIT_DURATION: "5s"  # 5s, 10s or 20s
#  CB_SLIDING_WINDOW: "5"
