apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service
  namespace: var17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      hostAliases:
        - ip: "10.60.3.27"
          hostnames:
            - "hl22.zil"
        - ip: "10.60.3.28"
          hostnames:
            - "hl23.zil"
      imagePullSecrets:
        - name: seryak0ff
      containers:
        - name: main-service
          image: seryak0ff/main-service:17.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: config
            - secretRef:
                name: db-credentials
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
