piVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: var17
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      imagePullSecrets:
        - name: seryak0ff
      containers:
        - name: analytics-service
          image: seryak0ff/analytics-service:17.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          envFrom:
            - configMapRef:
                name: config
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "1"
              memory: "1024Mi"
