apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: var17
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cG9zdGdyZXM=  # postgres
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=  # postgres