apiVersion: v1
kind: Service
metadata:
  name: analytics-service-nodeport
  namespace: var17
spec:
  type: NodePort
  selector:
    app: analytics-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 31702
